const productsData = {
    newProducts: [{
            id: 1,
            name: "Sữa Nan Optipro Plus số 3 5-HMO 1.5kg (1 - 2 tuổi)",
            image: "../IMG/sua-nan-nga-so-3-800g.jpg",
            price: 499000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sữa Aptamil Profutura Úc số 1 900g (0 - 6 tháng)",
            image: "../IMG/sua-aptamil-profutura-uc-so-1-900gr-new-0-6m.jpg",
            price: 331900,
            promotion: "new",
        },
        {
            id: 3,
            name: "Sữa Aptamil Profutura Úc số 2 900g (6 - 12 tháng)",
            image: "../IMG/sua-aptamil-profutura-uc-so-2-900gr-new-6-12m.jpg",
            price: 900000,
            decrease: 746000,
            discount: "-33%",
        },
        {
            id: 4,
            name: "Sữa Aptamil Profutura Úc số 3 900g (Trên 1 tuổi)",
            image: "../IMG/sua-aptamil-profutura-uc-so-3-900gr.jpg",
            price: 799000,
            promotion: "new",
        },

        {
            id: 5,
            name: "Sữa Meiji số 9 nội địa Nhật 800g (1 - 3 tuổi)",
            image: "../IMG/sua-meiji-so-9.jpg",
            price: 900000,
            promotion: "new",
        },
        {
            id: 6,
            name: "Sữa Blackmores Newborn số 1 900g (0 - 6 tháng)",
            image: "../IMG/sua-blackmores-so-1-900g.jpg",
            price: 900000,
            decrease: 781000,
            discount: "-21%",
        },
        {
            id: 7,
            name: "Sữa Blackmores Follow-on số 2 900g (6 - 12 tháng)",
            image: "../IMG/sua-blackmores-so-1-900g.jpg",
            price: 575000,
            decrease: 561000,
            discount: "-2%",
        },
        {
            id: 8,
            name: "Sữa Blackmores Toddler số 3 900g (Trên 12 tháng)",
            image: "../IMG/sua-blackmores-so-2-900g.jpg",
            price: 560000,
            decrease: 530000,
            discount: "-8%",
        },
        {
            id: 9,
            name: "Sữa Aptamil Profutura Úc số 1 900g (0 - 6 tháng)",
            image: "../IMG/sua-aptamil-duc-so-1-800g.jpg",
            price: 930000,
            promotion: "new",
        },
        {
            id: 10,
            name: "Sữa Aptamil Profutura Úc số 2 900g (6 - 12 tháng)",
            image: "../IMG/sua-aptamil-profutura-uc-so-2-900gr-new-6-12m.jpg",
            price: 902000,
        },
        {
            id: 11,
            name: "Sữa Aptamil Profutura Úc số 3 900g (Trên 1 tuổi)",
            image: "../IMG/sua-aptamil-profutura-uc-so-2-900gr-new-6-12m.jpg",
            price: 830000,
            promotion: "new",
        },
        {
            id: 12,
            name: "Sữa Nan Optipro Plus số 3 5-HMO 1.5kg (1 - 2 tuổi)",
            image: "../IMG/sua-nan-optipro-plus-so-3-5-hmo-15kg-1-2-tuoi.jpg",
            price: 789000,
        },
        {
            id: 13,
            name: "Sữa Aptamil Advanced Anh số 1 800g (0 - 6 tháng)",
            image: "../IMG/sua-bot-aptamil-advanced-anh-so-1-800g (1).jpg",
            price: 710000,
        },
        {
            id: 14,
            name: "Sữa Aptamil Advanced Anh số 2 800g (6 - 12 tháng)",
            image: "../IMG/sua-bot-aptamil-advanced-anh-so-1-800g.jpg",
            price: 720000,
            promotion: "new",
        },
        {
            id: 15,
            name: "Sữa A2 Úc nguyên kem 1kg (Trên 1 tuổi)",
            image: "../IMG/sua-bot-a2-uc-nguyen-kem-1kg-2y.jpg",
            price: 360000,
            decrease: 334000,
            discount: "-10%",
        },
    ],
    sacMayAnh: [{
            id: 1,
            name: "Sữa nan infinipro a2 số 3",
            image: "../IMG/sua-nan-infinipro-a2-so-3-800g-2-6-tuoi.jpg",
            price: 799000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sữa dinh dưỡng pha sẵn Nan Grow 110ml (Lốc 4 hộp)",
            image: "../IMG/sua-nuoc-nan-grow-110ml-loc-4.jpg",
            price: 50000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Sữa Meiji thanh Infant Formula 20 thanh (0 - 1 tuổi)",
            image: "../IMG/sua-meiji-thanh-infant-formula-540g-0-12-thang.jpg",
            price: 300000,
            decrease: 270000,
            discount: "-10%",
        },
        {
            id: 4,
            name: "Sữa Meiji thanh số 0 nội địa Nhật 30 thanh (0 - 1 tuổi)",
            image: "../IMG/sua-meiji-so-0-noi-dia-nhat-800g.jpg",
            price: 640000,
            promotion: "new",
        },

        {
            id: 5,
            name: "Sữa Meiji thanh số 9 nội địa Nhật 30 thanh (1 - 3 tuổi)",
            image: "../IMG/sua-meiji-so-9.jpg",
            price: 569000,
            promotion: "new",
        },
        {
            id: 6,
            name: "Sữa Nan Optipro Plus số 3 5HMO 800g (1 - 2 tuổi) ",
            image: "../IMG/sua-nuoc-nan-grow-110ml-loc-4.jpg",
            price: 472000,
            decrease: 463000,
            discount: "-2%",
        },
        {
            id: 7,
            name: "Sữa Meiji thanh nội địa Nhật số 0 thanh lẻ (0-1 tuổi)",
            image: "../IMG/sua-meiji-thanh-so-9-noi-dia-nhat-30-thanh-1-3-tuoi.jpg",
            price: 24000,
            decrease: 20000,
            discount: "-2%",
        },
        {
            id: 8,
            name: "Sữa GrowPLUS+ đỏ 900g (Từ 1-2 tuổi)",
            image: "../IMG/sua-growplus-do-900g-ho-tro-tang-can-tren-1-tuoi.jpg",
            price: 359000,
            decrease: 330000,
            discount: "-6%",
        },

        {
            id: 9,
            name: "Sữa GrowPLUS+ đỏ 1,5kg (Từ 1-2 tuổi)",
            image: "../IMG/sua-growplus-do-15kg-ho-tro-tang-can-tren-1-tuoi.jpg",
            price: 560000,
            promotion: "new",
        },
        {
            id: 10,
            name: "Sữa non pha sẵn GrowPLUS+ vàng 180ml (lốc 4 hộp) ",
            image: "../IMG/sua-non-pha-san-growplus-vang-180ml-loc-4-hop.jpg",
            price: 60000,
        },

    ],
    chanMayAnh: [{
            id: 1,
            name: "Sữa Morinaga Hagukumi số 1 800g (Từ 0-6 tháng)",
            image: "../IMG/sua-morinaga-hagukumi-so-1-800g-tu-0-6-thang.jpg",
            price: 549000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sữa Morinaga Kodomil số 3 hương vani 800g (Trên 3 tuổi)",
            image: "../IMG/sua-morinaga-kodomil-so-3-huong-vani-800g-tren-3-tuoi.jpg",
            price: 479000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Sữa ColosBaby Gold 0+ 400g (0 - 12 tháng)",
            image: "../IMG/sua-colosbaby-bio-gold-0-800g0-12thang.jpg",
            price: 249000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Sữa France Lait Lactofree 400g (Từ sơ sinh)",
            image: "../IMG/sua-france-lait-lactofree-400g-tu-so-sinh.jpg",
            price: 330000,
            decrease: 300000,
            discount: "-10%",
        },
        {
            id: 5,
            name: "Sữa ColosBaby Bio Gold 0+ 800g (0 - 12 tháng)",
            image: "../IMG/sua-colosbaby-bio-gold-1-800g-1-2y.jpg",
            price: 529000,
            decrease: 500000,
            discount: "-6%",
        },
        {
            id: 6,
            name: "Sữa HIKID vị vani 600g (1 - 9 tuổi)",
            image: "../IMG/sua-bot-hikid-vi-vani-600gr-1-9y.jpg",
            price: 520000,
            decrease: 490000,
            discount: "-6%",
        },
        {
            id: 7,
            name: "Sữa ColosBaby Bio Gold 1+ 800g (1 - 2 tuổi)",
            image: "../IMG/sua-colosbaby-gold-0400g-s0-12-thang.jpg",
            price: 489000,
        },
        {
            id: 8,
            name: "Sữa ColosBaby Bio IQ Gold 0+ 800g (0 - 12 tháng)",
            image: "../IMG/sua-colosbaby-gold-0400g-s0-12-thang.jpg",
            price: 529000,
        },
        {
            id: 9,
            name: "Sữa France Lait Lactofree 400g (Từ sơ sinh)",
            image: "../IMG/sua-france-lait-lactofree-400g-tu-so-sinh.jpg",
            price: 529000,
            promotion: "new",
        },

    ],
    voMayAnh: [{
            id: 1,
            name: "Sữa Nubone Step 1 750g (0 - 12 tháng)",
            image: "../IMG/sua-bot-nubone-plus-750g-1-10-tuoi.jpg",
            price: 632000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sữa Nubone Step 2 750g (1 - 3 tuổi)",
            image: "../IMG/sua-bot-nubone-step-1-750g-0-12-thang-tuoi.jpg",
            price: 695000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Sữa Nubone Plus+ 750g (1 - 10 tuổi)",
            image: "../IMG/sua-bot-nubone-plus-750g-1-10-tuoi.jpg",
            price: 642000,
            decrease: 630000,
            discount: "-2%",
        },
        {
            id: 4,
            name: "Sữa Colos Gain 0+ 800g (0 - 12 tháng)",
            image: "../IMG/sua-colos-gain-0-800g-0-12-thang.jpg",
            price: 369000,
            promotion: "new",
        },
        {
            id: 5,
            name: "Sữa Colos Gain 1+ 800g (1 - 10 tuổi)",
            image: "../IMG/sua-colos-gain-1-800g-1-10-tuoi.jpg",
            price: 349000,
            decrease: 342000,
            discount: "-2%",
        },
        {
            id: 6,
            name: "Sữa hạt Vegemil dành cho mẹ bầu và cho con bú",
            image: "../IMG/sua-hat-danh-cho-me-bau-190ml-vegemil-loc-4.jpg",
            price: 94000,
        },
        {
            id: 7,
            name: "Sữa bột Oggi Gold hỗ trợ tăng cân 900g (1-10 tuổi)",
            image: "../IMG/sua-oggi-suy-dinh-duong-gold-900g-1-10-tuoi.jpg",
            price: 333000,
        },
        {
            id: 8,
            name: "Sữa Colosbaby Gold D3K2 1+ 800g (1 - 2 tuổi)",
            image: "../IMG/sua-colosbaby-gold-d3k2-1-800g-1-2-tuoi.jpg",
            price: 489000,
            decrease: 440000,
            discount: "-10%",
        },
        {
            id: 9,
            name: "Sữa Colosbaby Gold D3K2 0+ 800g (0 - 1 tuổi)",
            image: "../IMG/sua-colosbaby-gold-d3k2-0-800g-0-1-tuoi.jpg",
            price: 529000,
            promotion: "new",
        },
        {
            id: 10,
            name: "Sữa Kidsmix Advanced số 1 400g (0 - 1 tuổi)",
            image: "../IMG/sua-bot-kidsmix-advanced-so-1-400g-0-1-tuoi.jpg",
            price: 351000,
            promotion: "new",
        },

    ],
    boLoc: [{
            id: 1,
            name: "Sữa Kidsmix Advanced số 2 800g (1 - 2 tuổi)",
            image: "../IMG/sua-bot-kidsmix-advanced-so-2-800g-12-24-thang.jpg",
            price: 650000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sữa PureLac Royal+ Toddler Formula số 3 800g",
            image: "../IMG/sua-bot-purelac-so-3-800g.jpg",
            price: 849000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Sữa ColosBaby IQ Gold 1+ 800g (1 - 2 tuổi)",
            image: "../IMG/sua-colosbaby-iq-gold-1-800g-1-2y.jpg",
            price: 489000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Sữa Nan Optipro Plus số 4 5HMO 800g (2 - 6 tuổi)",
            image: "../IMG/sua-nan-optipro-plus-so-4-5hmo-800g-2-6-tuoi-giao-bao-bi-ngau-nhien.jpg",
            price: 456000,
            decrease: 410000,
            discount: "-10%",
        },
        {
            id: 5,
            name: "Sữa Enfamil Enspire số 1 350g (0 - 12 tháng)",
            image: "../IMG/sua-enfamil-enspire-so-1-350g-0-12-thang.jpg",
            price: 512000,
            decrease: 460000,
            discount: "-10%",
        },
        {
            id: 6,
            name: "Thùng 48 hộp sữa non pha sẵn GrowPLUS+ 110ml",
            image: "../IMG/thung-48-hop-sua-non-pha-san-growplus-110ml.jpg",
            price: 448000,
        },
        {
            id: 7,
            name: "Sữa Meiji thanh Growing Up Formula 560g (1 - 3 tuổi)",
            image: "../IMG/sua-meiji-thanh-growing-up-formula-560g-1-3-tuoi.jpg",
            price: 393000,
        },
        {
            id: 8,
            name: "Sữa Morinaga số 1 dạng thanh 10 gói x 13g (0 - 6 tháng)",
            image: "../IMG/sua-morinaga-so-1-dang-thanh-0-6m-10-goi-x-13g.jpg",
            price: 98000,
            decrease: 96000,
            discount: "-2%",
        },
        {
            id: 9,
            name: "Sữa Nan Optipro Plus số 2 5-HMO 800g (6 - 12 tháng) ",
            image: "../IMG/sua-nan-optipro-plus-so-2-5-hmo-800g-6-12-thang.jpg",
            price: 528000,
            promotion: "new",
        },

    ],
    denLed: [{
            id: 1,
            name: "Sữa Abbott Grow pha sẵn hương vani 180ml (Lốc 4 hộp)",
            image: "../IMG/sua-nuoc-tt-grow-gold-vani-180ml-loc-4.jpg",
            price: 72000,
            decrease: 71000,
            discount: "-2%",
        },
        {
            id: 2,
            name: "Sữa Abbott Grow pha sẵn hương vani 110ml (Lốc 4 hộp)",
            image: "../IMG/sua-nuoc-tt-grow-gold-vani-110ml-loc-4.jpg",
            price: 51000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Sữa Abbott Grow số 3 900g (1 - 2 tuổi)",
            image: "../IMG/sua-bot-abbott-grow-3-g-powervani-900g.jpg",
            price: 306000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Sữa Nan Supreme Pro số 3 5-HMO 800g New (2 - 6 tuổi)",
            image: "../IMG/sua-nan-supremepro-so-3-800g.jpg",
            price: 538000,
            promotion: "new",
        },
        {
            id: 5,
            name: "Sữa Morinaga Hagukumi số 1 320g (0 - 6 tháng)",
            image: "../IMG/sua-morinaga-so-1-320g-new.jpg",
            price: 252000,
            decrease: 230000,
            discount: "-10%",
        },
        {
            id: 6,
            name: "Sữa Morinaga Chilmil số 2 320g (6 - 36 tháng)",
            image: "../IMG/sua-morinaga-so-2-320g-new.jpg",
            price: 239000,
            decrease: 210000,
            discount: "-10%",
        },
        {
            id: 7,
            name: "Sữa HiPP Combiotic Organic HMP & GOS số 3 800g",
            image: "../IMG/sua-hipp-organic-bo-sung-hmpgos-so-3-800g.jpg",
            price: 761000,
        },
        {
            id: 8,
            name: "Thùng 48 hộp sữa GrowPLUS+ 110ml (Trên 1 tuổi)",
            image: "../IMG/thung-48-hop-sua-growplus-110ml-tren-1-tuoi.jpg",
            price: 400000,
        },
        {
            id: 9,
            name: "Sữa Meiji thanh nội địa Nhật số 9 thanh lẻ (1-3 tuổi)",
            image: "../IMG/sua-meiji-thanh-noi-dia-nhat-so-9-thanh-le-1-3-tuoi.jpg",
            price: 22000,
            promotion: "new",
        },

    ],

};

const productsData2 = {
    newProducts: [{
            id: 1,
            name: "Sữa Meiji số 9 nội địa Nhật 800g (1 - 3 tuổi)",
            image: "../IMG/sua-meiji-so-9.jpg",
            price: 389000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sữa Meiji số 0 nội địa Nhật 800g (0 - 1 tuổi)",
            image: "../IMG/sua-meiji-so-0-noi-dia-nhat-800g.jpg",
            price: 479000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Sữa Nan Nga số 3 800g (Trên 1 tuổi)",
            image: "../IMG/sua-nan-nga-so-3-800g.jpg",
            price: 490000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Sữa PediaSure BA 400g (1 - 10 tuổi)",
            image: "../IMG/sua-bot-pediasurebavani-400g.jpg",
            price: 329000,
            promotion: "new",
        },
    ],
    popularProduct: [{
            id: 1,
            name: "Sữa Aptamil Đức số 1 800g (0 - 6 tháng)",
            image: "../IMG/sua-aptamil-duc-so-1-800g.jpg",
            price: 610000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Sữa Aptamil Đức số 2 800g (0 - 6 tháng)",
            image: "../IMG/sua-aptamil-duc-so-2-800g.jpg",
            price: 600000,
        },
        {
            id: 3,
            name: "Sữa Aptamil Đức số 3 800g (Trên 12 tháng)",
            image: "../IMG/sua-aptamil-duc-so-3-800g.jpg",
            price: 590000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Sữa Nan Nga số 4 800g (Trên 18 tháng)",
            image: "../IMG/sua-nan-nga-so-4-800g.jpg",
            price: 469000,
        },
    ],
    discountProduct: [{
            id: 1,
            name: "Sữa PediaSure hương vani 850g (1 - 10 tuổi)",
            image: "../IMG/sua-bot-pediasurebavani-850g.jpg",
            price: 626000,
            decrease: 563400,
            discount: "-10%",
        },
        {
            id: 2,
            name: "Sữa PediaSure Úc 850g Mẫu mới (1 - 10 tuổi)",
            image: "../IMG/sua-pediasure-uc-850g-mau-moi-1-10-tuoi.jpg",
            price: 799000,
            decrease: 719100,
            discount: "-10%",
        },
        {
            id: 3,
            name: "Sữa Aptamil Profutura Úc số 1 900g (0 - 6 tháng)",
            image: "../IMG/sua-aptamil-profutura-uc-so-1-900gr-new-0-6m.jpg",
            price: 925000,
            decrease: 832500,
            discount: "-10%",
        },
        {
            id: 4,
            name: "Sữa Aptamil Profutura Úc số 2 900g (6 - 12 tháng)",
            image: "../IMG/sua-aptamil-profutura-uc-so-2-900gr-new-6-12m.jpg",
            price: 925000,
            decrease: 832500,
            discount: "-10%",
        },
    ],
};